[build]
  node_version = "18"


[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@langchain/community/tools/serpapi"]
  included_files = ["./node_modules/@langchain/**"]
  external_node_modules = ["@langchain/community"]
  force_include_body = true